name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
Note: If you also want to include the private repository, register the "personal access token" in the repository and set it to GITHUB_TOKEN specified in the workflow file.

This will add the action to the repository.

Environment variables
GITHUB_TOKEN : (required) access token
USERNAME : (required) target user name (or specify with an argument).
MAX_REPOS : (optional) max repositories, default 100 - since ver. 0.2.0
SETTING_JSON : (optional) settings json file path. See sample-settings/*.json and src/type.ts in yoshi389111/github-profile-3d-contrib repository for details. - since ver. 0.6.0
step 3. Manually launch the action
Launch the added action.

Actions -> GitHub-Profile-3D-Contrib -> Run workflow
The profile image is generated with the following paths.

profile-3d-contrib/profile-green-animate.svg
profile-3d-contrib/profile-green.svg
profile-3d-contrib/profile-season-animate.svg
profile-3d-contrib/profile-season.svg
profile-3d-contrib/profile-south-season-animate.svg
profile-3d-contrib/profile-south-season.svg
profile-3d-contrib/profile-night-view.svg
profile-3d-contrib/profile-night-green.svg
profile-3d-contrib/profile-night-rainbow.svg
profile-3d-contrib/profile-gitblock.svg
Alternatively, if SETTING_JSON is specified, the following image will be generated.

profile-3d-contrib/profile-customize.svg
example: green version
